apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-weatherforecast-csharp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: my-weatherforecast-csharp
  namespace: my-apps
spec:
  params:
  - name: clusterBuilder
    value: base
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/ncarlson/weather-forecast-test.git
      ref:
        branch: main